server:
  port: 8000

logging:
  path: logs

database:
  host: localhost
  port: 5432
  name: diff
  username: sa
  password:
  sufix: ${database.host}:${database.port}/${database.name}

spring:
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:h2:mem:${database.name};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: {database.username}
    password: {database.password}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
